---
# Assumptions: 
#    - postmaster  is not running
#    - ansible executes as unix user 'postgres'
#    - cluster has been initialized and pg_hda allows role 'postres'to connect 
#    - we will not configure osx hosts because psycopg2 might be hard to install through macports
# Post conditions:
#   - postmaster might be running, depending on variable  "run_cluser" in ../default/meta.yml
#   - pg_hba.conf is updated
#   - created postgres roles with passwords
#   - added to template1
#   - created  databases, extensions, languages, and set privs
#   - enabled replication via uses 'postgres' and 'replication' (see pg_hba.conf)

  - name:           fail unless ansible executing as unix user postgres
    when:           not (ansible_user_id == "postgres")
    fail:           msg="Detected ansible_user_id='{{ ansible_user_id}}'. This role must run as 'postgres'"

  - name:           fail if we are insalling to osx hosts
    when:           ansible_os_family == "Darwin"
    fail:           msg="Detected ansible_os_family='{{ ansible_os_family}}'. We won't configure osx hosts."

  - name:           ensure postmaster is running 
    shell:          "pg_ctl -D {{ cluster }} start"
    environment:  
      PATH:        "{{ ansible_env.HOME }}/dist-pg/bin:{{ ansible_env.PATH}}:/usr/bin"
############################### Roles  ##############################################################################

  # need it for next step
  - command:           echo  "{{postgres_passwd}}postgres"
    register:          newvar

  - name:             "role {{newvar.stdout}}"
    postgresql_user:  name=postgres   role_attr_flags=superuser  port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost" password="md5{{ newvar.stdout |hash('md5')}}"  encrypted=yes  ssl_mode=prefer

  - name:             role replication
    postgresql_user:  name=replication   role_attr_flags=replication  port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost" password="md5{{'silver''replication'|hash('md5')}}"  encrypted=yes  ssl_mode=prefer

  - name:             role ioannis
    postgresql_user:  name=ioannis        role_attr_flags=CREATEDB  port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost" password="md5{{ 'silver''ioannis'|hash('md5') }}"  encrypted=yes  ssl_mode=prefer

  - name:             role nagios
    postgresql_user:  name=nagios    port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost" password="md5{{'silver''nagios'|hash('md5')}}"  encrypted=yes  ssl_mode=prefer

#################################### config_files ##################################################################
  - name:            pg_*.conf
    copy:            src="{{ item }}"  dest="{{ cluster}}/"  owner=postgres  mode=0640
    with_fileglob:
       - pg_*.conf
################################## template1   ######################################################################
  - name: plpgsql
    postgresql_lang:  db=template1  lang=plpgsql   trust=yes  state=present port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost"
    
################################### Databases  #####################################################################
  - name:   db bench
    postgresql_db: name="bench" owner="ioannis" encoding="UTF-8" lc_collate="en_US.UTF-8"  template=template0  port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost"

  - name:   db ioannis
    postgresql_db: name="ioannis" owner="ioannis" encoding="UTF-8" lc_collate="en_US.UTF-8"  template=template0  port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost"

################################# Extensions  #######################################################################
  - name:            ext for database ioannis
    postgresql_ext:  name={{item}}  db=ioannis port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost"
    with_items:
         - pgtap
           #- pg_stat_statements #- pg_qualstats #- pg_stat_kcache


################################ Privs     ###########################################################################
  - name:  privs for database postgres 
    postgresql_privs:   db="postgres"  privs=CONNECT  type=database  roles="{{item}}" port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost"
    with_items:
        - nagios
        - ioannis

  - postgresql_privs:   db="postgres" grant_option="no"  privs="INSERT,UPDATE"  type="table" obj="ALL_IN_SCHEMA"  schema="public" roles="{{item}}"  port="{{ pport }}" login_password="{{postgres_passwd}}"  login_host="localhost"
    with_items:
        - nagios

################################## Reload, then Stop postmaster unless user wanted otherwise
  - name:            reload {{ cluster}} 
    shell:          "pg_ctl -D {{ cluster }} reload"
    environment:  
          PATH:     "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/dist-pg/bin:/usr/bin"

  - name:            keep postmaster running ?
    when:            not (keep_running)
    ignore_errors:   yes
    shell:          "pg_ctl -D {{ cluster }} stop"
    environment:  
          PATH:     "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/dist-pg/bin:/usr/bin"
